'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Tours', [
      {
        ownerId: 5,
        name: 'Тур по Байкалу',
        location: 'Байкал',
        startOfTheTour: new Date('2024-05-07'),
        endOfTheTour: new Date('2024-05-27'),
        price: 95000,
        description:
          'Озеро Байкал – огромное древнее озеро в горах Сибири к северу от монгольской границы. Байкал считается самым глубоким озером в мире.',
        adminAproved: true,
        duration: '20',
        tourPhoto: 'b9a5dc0f-da9c-449e-867c-7a54b8193369.jpg',
        maxPeoples: 20,
        longitude: '53.405332',
        latitude: '107.673058',
        remaindQuantity: 15,
        reservedQuantity: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 2,
        name: 'ыпваыап',
        location: 'место',
        startOfTheTour: new Date('2022-03-07'),
        endOfTheTour: new Date('2024-03-08'),
        price: 10,
        description: 'не очень классный тур',
        duration: '1',
        adminAproved: false,
        tourPhoto: null,
        maxPeoples: 4,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 3,
        reservedQuantity: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        name: 'Тур по Шуе',
        location: 'Шуя',
        startOfTheTour: new Date('2024-03-27'),
        endOfTheTour: new Date('2024-03-29'),
        price: 1000000,
        description: 'Слишком классный тур, возможен буст навыков джаваскрипта',
        adminAproved: true,
        duration: '2',
        tourPhoto: '2e9d95785efbdc2b7837a48d362c473c.jpeg',
        maxPeoples: 3,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 2,
        reservedQuantity: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 6,
        name: 'Подъем на Эльбрус',
        location: 'Кавказ',
        startOfTheTour: new Date('2024-03-17'),
        endOfTheTour: new Date('2024-03-28'),
        price: 295000,
        description:
          'Эльбрус — это самая большая гора России и Европы. 5 642 метра над уровнем моря! Эльбрус воспет поэтами и прославлен альпинистами. Если для вас восхождение — слишком рискованный и трудный шаг, приезжайте хотя бы просто посмотреть на этого великана.\nВ Приэльбрусье можно недорого покататься на горных лыжах, попить минеральную воду нарзан и насладиться кавказским гостеприимством с шашлыком и винами.',
        adminAproved: true,
        duration: '11',
        tourPhoto: '00_elbrus.jpg',
        maxPeoples: 20,
        longitude: '43.34396684507407',
        latitude: '42.44134823323462',
        remaindQuantity: 2,
        reservedQuantity: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 5,
        name: 'Экскурсия по кампусу',
        location: 'Москва',
        startOfTheTour: new Date('2024-04-21'),
        endOfTheTour: new Date('2024-04-22'),
        price: 0,
        description: 'Ознакомление с кампусом',
        adminAproved: true,
        duration: '1',
        tourPhoto: 'birthday-mobile.webp',
        maxPeoples: 1,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 1,
        reservedQuantity: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 5,
        name: 'Путь к горе Арарат',
        location: 'Турция',
        startOfTheTour: new Date('2024-05-21'),
        endOfTheTour: new Date('2024-08-21'),
        price: 47000,
        description: 'Без подьема',
        adminAproved: true,
        duration: '112',
        tourPhoto: 'ararat4.jpg',
        maxPeoples: 4,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 4,
        reservedQuantity: 0,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        name: 'Куршская коса',
        location: 'Калининград',
        startOfTheTour: new Date('2024-09-18'),
        endOfTheTour: new Date('2024-09-13'),
        price: 55000,
        description:
          'Куршская коса в целом представляет собой длинный (98 км) и узкий (0.35 – 3.8 км) песчаный полуостров, вытянутый с юго-запада на северо-восток от г. Зеленоградска до литовского г. Клайпеда и отделяющий от Балтийского моря пресноводный Куршский залив. Это самая длинная в мире песчаная пересыпь.',
        adminAproved: true,
        duration: '5',
        tourPhoto: '89e1b31e36070207303a4218dcd41c82.jpg',
        maxPeoples: 13,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 2,
        reservedQuantity: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        name: 'Хибины',
        location: ' Мурманск',
        startOfTheTour: new Date('2024-05-02'),
        endOfTheTour: new Date('2024-05-27'),
        price: 90000,
        description:
          'Хибины — это горы на Кольском полуострове. Имеют мягкий рельеф и отличаются потрясающей природой. Там произрастает и обитает почти вся Красная книга. Большую часть года горный массив остаётся заснеженным, благодаря чему привлекает любителей горнолыжного спорта. Основные горнолыжные комплексы – на горах Айкуайвенчорр и Кукисвумчорр. Кататься можно с ноября по июнь.',
        adminAproved: true,
        duration: '25',
        tourPhoto: 'Xibiny_1599817901-1024x512.jpg',
        maxPeoples: 30,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 12,
        reservedQuantity: 18,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 5,
        name: 'Экскурсия в Кижи',
        location: 'Карелия',
        startOfTheTour: new Date('2024-04-21'),
        endOfTheTour: new Date('2024-04-23'),
        price: 8000,
        description:
          'Кижи представляют собой архитектурный ансамбль из двух деревянных церквей и колокольни XVIII–XIX веков, выстроенных без гвоздей. Это одна из главных российских достопримечательностей. Находится на острове в Онежском озере и является частью государственного историко-архитектурного музея «Кижи». Это отличное место для изучения истории и ремёсел, а также размышлений на вечные темы.',
        adminAproved: true,
        duration: '2',
        tourPhoto: 'kizhi-vid-2600.jpg',
        maxPeoples: 7,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 7,
        reservedQuantity: 0,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        name: 'Рускеала',
        location: 'Карелия',
        startOfTheTour: new Date('2024-03-15'),
        endOfTheTour: new Date('2024-03-18'),
        price: 18900,
        description:
          'Рускеала — это село с уникальной природой и славной историей, вблизи которого расположен одноимённый горный парк. Он включает в себя Мраморный каньон и Рускеальский провал. Каньон окружён отвесными скалами, гротами и штольнями. Он заполнен чистыми грунтовыми водами, и поэтому абсолютно прозрачен. А Рускеальский провал уникален тем, что в его дальних частях никогда не тает лёд. В парке можно прокатиться по каньону на лодке, прыгнуть с его обрыва или поплавать по заброшенным шахтам с аквалангом.',
        adminAproved: true,
        duration: '13',
        tourPhoto: '516b56ed2a7bf406edb17dea829a92cb.jpg',
        maxPeoples: 4,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 4,
        reservedQuantity: 0,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 5,
        name: 'Кезенойам',
        location: 'Чечня',
        startOfTheTour: new Date('2024-05-22'),
        endOfTheTour: new Date('2024-05-24'),
        price: 66200,
        description:
          'Кезенойам — это озеро на южном склоне Андийского хребта. Является самым большим (1,7 квадратного километра) и глубоким (до 74 метров) естественным водоёмом Северного Кавказа. Кезенойам поражает своей прозрачностью — в хорошую погоду можно увидеть резвящуюся на дне форель.',
        adminAproved: true,
        duration: '2',
        tourPhoto: 'kezenoyam_Andrei-Kholmov-Shutterstock_1599818329.jpg',
        maxPeoples: 2,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 2,
        reservedQuantity: 0,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 5,
        name: 'Петергоф экскурсия',
        location: 'Санкт-Петербург',
        startOfTheTour: new Date('2024-06-19'),
        endOfTheTour: new Date('2024-06-21'),
        price: 7500,
        description:
          'Петергоф — это дворцово-парковый ансамбль на южном берегу Финского залива. Наряду с другими архитектурными памятниками является визитной карточкой Санкт-Петербурга и частью Всемирного наследия ЮНЕСКО.',
        adminAproved: true,
        duration: '1',
        tourPhoto: 'Petergof_1599817989.jpg',
        maxPeoples: 5,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 1,
        reservedQuantity: 4,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 5,
        name: 'Свияжск',
        location: 'Татарстан',
        startOfTheTour: new Date('2024-03-21'),
        endOfTheTour: new Date('2024-03-21'),
        price: 17500,
        description:
          'Свияжск — это маленькое село с большой историей. В 1551–1552 годах град Свияжск помог войскам Ивана Грозного взять Казань. Село расположено в Зеленодольском районе Татарстана. Отделено от большой земли Куйбышевским водохранилищем, летом к нему курсирует пассажирский теплоход.',
        adminAproved: true,
        duration: '1',
        tourPhoto: 'Sviyazhsk_Andy-Shell-Shutterstock_1599818117.jpg',
        maxPeoples: 14,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 2,
        reservedQuantity: 12,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        name: 'Шиханы',
        location: 'Башкортостан',
        startOfTheTour: new Date('2024-04-21'),
        endOfTheTour: new Date('2024-04-25'),
        price: 31500,
        description:
          'Шиханами называются окаменелые рифовые массивы. Тысячелетия назад здесь было тёплое море. Поэтому внутри шихан – залежи каменной соли и известняка.',
        adminAproved: true,
        duration: '4',
        tourPhoto: 'SHixany_1599818138.jpg',
        maxPeoples: 14,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 14,
        reservedQuantity: 0,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 5,
        name: 'Эльтон',
        location: 'Волгоград',
        startOfTheTour: new Date('2024-06-28'),
        endOfTheTour: new Date('2024-06-29'),
        price: 52000,
        description:
          'Эльтон – это солёное озеро недалеко от границы с Казахстаном. Самое большое по площади минеральное озеро в Европе и одно из самых минерализованных в мире. Золотисто-розовый водоём окаймлён белоснежными кристаллами, а вокруг — потрясающей красоты ромашковые степи.',
        adminAproved: true,
        duration: '1',
        tourPhoto: 'e854ca23920711ee801af6c574779d3e_upscaled.jpg',
        maxPeoples: 5,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 1,
        reservedQuantity: 4,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        name: 'Столбы выветривания',
        location: 'Коми',
        startOfTheTour: new Date('2024-11-24'),
        endOfTheTour: new Date('2024-11-29'),
        price: 26000,
        description: 'Маньпупунёр, или Столбы́ выве́тривания — геологический памятник в Троицко-Печорском районе Республики Коми России. Находятся на территории Печоро-Илычского заповедника на горе Мань-Пупу-нёр, в междуречье рек Илыч и Печоры.',
        adminAproved: true,
        duration: '5',
        tourPhoto: 'manpupuner01.jpg',
        maxPeoples: 8,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 8,
        reservedQuantity: 0,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        name: 'Кунгурская пещера',
        location: 'Пермь',
        startOfTheTour: new Date('2024-05-02'),
        endOfTheTour: new Date('2024-05-08'),
        price: 9000,
        description:
          'Сталактиты, сталагмиты, огромные гроты с ледяными узорами и кристально чистые озёра — всё это Кунгурская пещера. Она расположена на окраине города Кунгур, что в сотне километров от Перми. Возраст пещеры около 10–12 тысяч лет, а первые письменные упоминания о ней встречаются с XVIII века. Неудивительно, что за это время пещера обросла не только сталактитами, но и легендами. Для посещения оборудованы полтора километра пещеры.',
        adminAproved: true,
        duration: '6',
        tourPhoto: 'kungur.jpg',
        maxPeoples: 25,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 20,
        reservedQuantity: 5,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 5,
        name: 'Таганай',
        location: 'Челябинская область',
        startOfTheTour: new Date('2024-03-21'),
        endOfTheTour: new Date('2024-03-22'),
        price: 28999,
        description: 'Без подьема',
        adminAproved: true,
        duration: '1',
        tourPhoto: 'TaganayArtyem_Kharchenko-Shutterstock_1599818475.jpg',
        maxPeoples: 1,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 2,
        reservedQuantity: 0,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 5,
        name: 'Кучерлинские озёра',
        location: 'Алтай',
        startOfTheTour: new Date('2024-07-15'),
        endOfTheTour: new Date('2024-07-17'),
        price: 37000,
        description: 'Без подьема',
        adminAproved: true,
        duration: '2',
        tourPhoto: 'Lake-Kucherla_diy13-Shutterstock_1599818512.jpg',
        maxPeoples: 5,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 2,
        reservedQuantity: 3,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        name: 'Путорана',
        location: 'Красноярский край',
        startOfTheTour: new Date('2024-03-24'),
        endOfTheTour: new Date('2024-03-27'),
        price: 43600,
        description: 'Без подьема',
        adminAproved: true,
        duration: '3',
        tourPhoto: 'Putorana_Serg-Zastavkin-Shutterstock_1599819207.jpg',
        maxPeoples: 15,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 15,
        reservedQuantity: 0,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 3,
        name: 'Ленские столбы',
        location: 'Якутия',
        startOfTheTour: new Date('2024-03-21'),
        endOfTheTour: new Date('2024-03-26'),
        price: 25000,
        description: 'Без подьема',
        adminAproved: true,
        duration: '5',
        tourPhoto: 'e7bbfed97c444b708a232cc135a9cd26-1920x1286.jpg',
        maxPeoples: 25,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 22,
        reservedQuantity: 3,
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date(),
      },
      {
        ownerId: 6,
        name: 'Гамсутль',
        location: 'Дагестан',
        startOfTheTour: new Date('2021-03-18'),
        endOfTheTour: new Date('2021-03-28'),
        price: 60000,
        description:
          'Древнейшее поселение Кавказа, раскинувшееся на самой вершине горы, его ещё называют местным Мачу-Пикчу. Гротескный аул-призрак был возведён на перекрёстке дорог Великого шёлкового пути, чтобы встречать торговые караваны, а со временем пришёл в упадок и местные жители его покинули. С вершины аула открывается вид на горы, скалистые ущелья и ближайшие посёлки. Здесь можно пройтись по безмолвным средневековым улицам и, если повезёт, встретить «последнего жителя Гамстуля» Зиявудина — официально он здесь не живёт, но приезжает каждый день из своего села, чтобы восстанавливать домик, в котором планирует встречать и поить чаем туристов.',
        adminAproved: true,
        duration: '10',
        tourPhoto: 'd2592b990a03d05a8303ab8c7fd49a8e5cf79894-uz8Ys0Wmc.jpg',
        maxPeoples: 6,
        longitude: '55',
        latitude: '55',
        remaindQuantity: 2,
        reservedQuantity: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Tours', null, {});
  },
};
